BUILDDIR ?= ../../build
override BUILDDIR := $(abspath $(BUILDDIR))

.PHONY: build clean

CC_FILES := $(wildcard *.cc)
build: $(CC_FILES)
	@echo "Building collective_communication (does nothing for now). Files" $^

clean:
	@echo "Cleaning collective_communication (does nothing for now)."
