name: Build and push Docker images to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space before build
        run: |
          df -h
          docker system df
          docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU for cross-cpu arch build
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log push target
        run: echo "Pushing to ${{ vars.DOCKERHUB_USERNAME }}/custom_nccl:latest"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/custom_nccl:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Inspect/verify build and push
        run: docker image inspect ${{ vars.DOCKERHUB_USERNAME }}/custom_nccl:latest
      - name: Cleanup Docker system
        run: |
          docker system prune -f
          docker builder prune -f
          df -h